name: wellness_visualizer

concurrency:
  group: $-$
  cancel-in-progress: true

permissions: read-all

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    if: ${{ !contains(fromJSON('["dependabot[bot]", "renovate[bot]", "snyk-bot", "allcontributors[bot]"]'), github.actor) }}
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Ensure Commit is Semantic
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          wip: false

  build:
    if: ${{ !contains(fromJSON('["dependabot[bot]", "renovate[bot]", "snyk-bot", "allcontributors[bot]"]'), github.actor) }}
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout with Submodules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Dependencies
        run: flutter pub get --enforce-lockfile

      - name: ✨ Check Formatting
        run: |
          dart format --line-length 120 --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: flutter analyze lib test

      - name: 🧪 Run Tests
        run: flutter test --coverage --concurrency=4 --test-randomize-ordering-seed=random --dart-define="FLUTTER_TEST=true"

      - name: 🎯 Filter Coverage Files
        run: |
          sudo apt-get update && sudo apt-get install -y lcov
          lcov --remove coverage/lcov.info "**/*.g.dart" "**/l10n" -o coverage/lcov_filtered.info --ignore-errors unused

      - name: 📈 Upload filtered coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov_filtered.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  spell-check:
    if: ${{ !contains(fromJSON('["dependabot[bot]", "renovate[bot]", "snyk-bot", "allcontributors[bot]"]'), github.actor) }}
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🪄 Spell Check
        uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          incremental_files_only: false
          root: .
          verbose: false
